name: dart_validate
description: Validate stat.
# version: 0.1.0
# author: jack tok <anan.untha@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.4.2

dev_dependencies:
  test: ^1.0.0
